### ISSUE TITLE
no molecule rendered

### ISSUE THREAD

**Issue by loriab** [gabrielelanaro/chemview#34] opened 2016-05-04 02:52 UTC
I'm sorry to open a ticket for an aspect that no one else seems to have had trouble with, but I can't get anything to render with chemview. I've installed decent versions of all the dependencies through pip or conda (below shows mostly pip, but I've another try that's mostly conda to same result). chemview itself is installed from a git clone through `pip install .` to get a recent version that's Jupyter-compatible. Running the basic tutorial gives only warnings (no errors) but also no rendered molecule. Any suggestions as to what I'm doing wrong?

<img width="998" alt="screen shot 2016-05-03 at 10 19 35 pm" src="https://cloud.githubusercontent.com/assets/2314730/15004093/c90b1b82-1180-11e6-8d03-592741510945.png">

```
>>> conda list
chemview                  0.6                       <pip>
ipykernel                 4.3.1                    py27_0    defaults
ipython                   4.1.2                    py27_2    defaults
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py27_0    defaults
ipython-qtconsole         3.1.0                    py27_0    defaults
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                4.1.1                    py27_0    defaults
jupyter                   1.0.0                     <pip>
jupyter-client            4.2.2                     <pip>
jupyter-console           4.1.1                     <pip>
jupyter-core              4.1.0                     <pip>
jupyter_client            4.2.2                    py27_0    defaults
jupyter_core              4.1.0                    py27_0    defaults
matplotlib                1.4.3                np19py27_2    defaults
nglview                   0.4                       <pip>
notebook                  4.2.0                    py27_0    defaults
numba                     0.14.0               np19py27_0    http://repo.continuum.io/pkgs/free/osx-64/numba-
numpy                     1.9.2                    py27_0    defaults
openbabel                 2.3.2                    py27_0    https://conda.binstar.org/psi4/osx-64/openbabel-2.3.2-
python                    2.7.11                        0    defaults
traitlets                 4.2.1                    py27_0    defaults
vapory                    0.1.1                     <pip>
```

**Comment by yalcinozhabes** [comment] 2016-05-04 03:01
Do you see any errors in the JavaScript console?

**Comment by hainm** [comment] 2016-05-04 03:02
hi, can you try to run the 4th-cell again? 

but like @yalcinozhabes said, you can open KS console by right clicking and choose Inspect (Chome).

**Comment by loriab** [comment] 2016-05-04 03:18
Well, there _were_ many errors when I located the JS console. But after cleaning the log for a fresh kernel restart and execution, there were no new ones generated.

```
Kernel: kernel_restarting (b87c463f-3c0f-48a3-96d8-ec38c3542278)
main.min.js:22356 Kernel: kernel_created (b87c463f-3c0f-48a3-96d8-ec38c3542278)
main.min.js:22709 Starting WebSockets: ws://localhost:8890/api/kernels/b87c463f-3c0f-48a3-96d8-ec38c3542278
main.min.js:22356 Kernel: kernel_connected (b87c463f-3c0f-48a3-96d8-ec38c3542278)
main.min.js:22356 Kernel: kernel_ready (b87c463f-3c0f-48a3-96d8-ec38c3542278)
```

System log (OS X Yosemite) has entries "Google Chrome Helper: Couldn't set selectedTextBackgroundColor from default ()" and "AppleCameraAssistant: *** LOG MESSAGE QUOTA EXCEEDED – SOME MESSAGES FROM THIS PROCESS HAVE BEEN DISCARDED".

**Comment by gabrielelanaro** [comment] 2016-05-04 16:59
Hi @loriab thanks for taking the time to write the very detailed bug report. I can reproduce the bug and I suspect this is because of some ipywidgets update. I'm working on it should be fixed soon. I'll keep you updated

**Comment by loriab** [comment] 2016-05-04 17:06
Oh good, I'm not crazy. Thanks, I look forward to trying out chemview.

**Comment by gabrielelanaro** [comment] 2016-05-04 18:48
@loriab I opened an issue in the ipywidgets repo to get some help. In the meantime you can try downgrade notebook:

conda install notebook=4.1
conda install ipywidgets=4.0 # not sure ipywidget version affects anything

**Comment by loriab** [comment] 2016-05-05 03:14
Downgrading the notebook alone does the trick. Thanks!

**Closed** 2016-06-16 07:35 UTC
Labels: bug
